[package]
name = "my_counter"
version = "1.0.0"
authors = []

[addresses]
counter_addr='a2860e98cec346e494daa79d20c790635b67eb92397f0f27c65a8de5ee09a3b9'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
